# Generated by Django 6.0.3 on 2026-03-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_image_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='static_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
